api:
  build: ./api
  ports: 
    - 3000:3000
  volumes:
    - ./api:/go/src/github.com/brunobandev/tournament-api/api
  links:
    - database
  environment:
    - DB_NAME=tournament

database:
  image: mongo:3.2
  command: mongod --smallfiles --quiet --logpath=/dev/null